spring:
    config:
        import: "optional:configserver:${CLOUD_CONFIG_IMPORT_URL}"
    cloud:
        config:
            name: feed
            profile: dev

management:
    endpoints:
        web:
            exposure:
                include: health, refresh, busrefresh
            base-path: /
            path-mapping:
                health: /
